#!/bin/sh

FT=$(file -b "$1") || "$1"

case "${FT}" in
  *"text"*)
    head -100 "$1"
    ;;
  "directory")
    tree -L 1 --noreport -C "$1"
    ;;
  *"No such file or directory"*)
    echo "$1"
    ;;
  *)
    echo "$FT"
esac
